# Generated by Django 5.2.7 on 2025-10-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oct',
            fields=[
                ('indice_sic', models.BigAutoField(primary_key=True, serialize=False)),
                ('oct', models.CharField(blank=True, max_length=255, null=True)),
                ('linea', models.CharField(blank=True, max_length=255, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_1', models.BigIntegerField(blank=True, null=True)),
                ('telefono_2', models.BigIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(blank=True, null=True)),
                ('creado_num', models.BigIntegerField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('asignado_a', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_disponible', models.IntegerField(blank=True, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sic_oct',
            },
        ),
        migrations.CreateModel(
            name='OctDetalle',
            fields=[
                ('indice_sic_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('indice_sic', models.BigIntegerField()),
                ('creado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(blank=True, null=True)),
                ('creado_num', models.BigIntegerField(blank=True, null=True)),
                ('resultado_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('tipificacion_positiva', models.CharField(blank=True, max_length=255, null=True)),
                ('tipificacion_negativa', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_date', models.DateField(blank=True, null=True)),
                ('creado_time', models.TimeField(blank=True, null=True)),
                ('creado_key_time', models.CharField(blank=True, max_length=50, null=True)),
                ('indice_tipo_respuesta', models.IntegerField(blank=True, null=True)),
                ('indice_respuesta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sic_oct_detalles',
            },
        ),
        migrations.CreateModel(
            name='OctHeader',
            fields=[
                ('indice', models.BigAutoField(primary_key=True, serialize=False)),
                ('oct', models.CharField(max_length=255)),
                ('fecha_oct', models.DateField(blank=True, null=True)),
                ('linea', models.CharField(blank=True, max_length=255, null=True)),
                ('script', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sic_oct_header',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('indice_programacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('indice_sic', models.BigIntegerField()),
                ('codigo_sucursal', models.IntegerField(blank=True, null=True)),
                ('fecha_aprox', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sic_programaciones',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('indice_respuesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('indice_tipo_respuesta', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sic_respuestas',
            },
        ),
        migrations.CreateModel(
            name='TipoRespuesta',
            fields=[
                ('indice_tipo_respuesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_respuesta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sic_tipo_respuestas',
            },
        ),
    ]
