# Generated by Django 5.2.7 on 2025-10-29 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('regimen', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion_eps', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_eps', models.CharField(blank=True, max_length=50, null=True)),
                ('update_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('update_telefono_1', models.BigIntegerField(blank=True, null=True)),
                ('update_telefono_2', models.BigIntegerField(blank=True, null=True)),
                ('update_email', models.CharField(blank=True, max_length=255, null=True)),
                ('portabilidad', models.CharField(blank=True, max_length=255, null=True)),
                ('cohorte_prev', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_gpn', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_bd', models.IntegerField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('f_inicio_port', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fin_port', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_poblacion', models.CharField(blank=True, max_length=255, null=True)),
                ('excento_c_mod', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria_c_mod', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_c_mod', models.FloatField(blank=True, null=True)),
                ('queja_activa', models.CharField(blank=True, max_length=255, null=True)),
                ('f_ultima_queja', models.CharField(blank=True, max_length=255, null=True)),
                ('quejas_last_6m', models.IntegerField(blank=True, null=True)),
                ('tipo_población', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_completo_usuario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sig_afiliados',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('indice_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sig_departamentos',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo_sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_centro_costo', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_sucursal', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_operador', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_operador', models.CharField(blank=True, max_length=50, null=True)),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_operativa', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('microtic', models.CharField(blank=True, max_length=50, null=True)),
                ('nit_operador', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_sucursal', models.CharField(blank=True, max_length=255, null=True)),
                ('activa', models.IntegerField(blank=True, null=True)),
                ('grupo_gpn', models.IntegerField(blank=True, null=True)),
                ('calificador', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sig_sucursales',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('indice_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=255)),
                ('indice_departamento', models.ForeignKey(db_column='indice_departamento', on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='sig_base.departamento')),
            ],
            options={
                'db_table': 'sig_municipios',
            },
        ),
    ]
